blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/OWNER/REPO/security/advisories
    about: Please use private vulnerability reporting for security issues
